#include <stdio.h>
#include <stdlib.h>

int main()
{
    printf("Please input weekSeq in 2015(1-53):\n");
    int week,month,day,a1,a2,m;
    scanf("%d",&week);
    if(week==1)
        {
         a1=1;
         a2=4;
        }
    if(week>1&&week<=53)
        {
         a1=(week-2)*7+5;
         a2=a1+6;
        }
    printf("No.%d week starts from No.%d day to No.%d day in 2015.\n",week,a1,a2);
    printf("#w:\tMon.\tTue.\tWed.\tThu.\tFri.\tSta.\tSun.\n");
    m=a1;
    printf("\b%d\t",week);
    while(m<=a2)
        {
         if(m==1)
            {
             printf("\t\t\t");
            }
         if(m<=31)
            {
             month=1;
             day=m;
            }
         if(m>31&&m<=59)
            {
             month=2;
             day=m-31;
            }
         if(m>59&&m<=90)
            {
             month=3;
             day=m-59;
            }
          if(m>90&&m<=120)
            {
             month=4;
             day=m-90;
            }
           if(m>120&&m<=151)
            {
             month=5;
             day=m-120;
            }
            if(m>151&&m<=181)
            {
             month=6;
             day=m-151;
            }
             if(m>181&&m<=212)
            {
             month=7;
             day=m-181;
            }
             if(m>212&&m<=243)
            {
             month=8;
             day=m-212;
            }
             if(m>243&&m<=273)
            {
             month=9;
             day=m-243;
            }
             if(m>273&&m<=304)
            {
             month=10;
             day=m-273;
            }
             if(m>304&&m<=334)
            {
             month=11;
             day=m-304;
            }
            if(m>334&&m<=365)
            {
             month=12;
             day=m-334;
            }
            printf("%d.%d\t",month,day);
            m++;
        }
    return 0;
}
